version: "3.5"
services:
  spark-master-train-bike-conjunto:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master-train-bike-conjunto
    ports:
      - "8080:8080"
      - "7077:7077"
      - "9002:9002"
      - "4040:4040"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
    networks:
         - ckan_yoda
    command: bash -c "sh /prediction-job/spark-jobs/run-spark-jobs-train.sh"
    volumes:
      - ./prediction-job:/prediction-job
     
networks:
  ckan_yoda:
    external: true
    name: ckan_yoda